version: '2'
services:
    hipsterapp-app:
        image: hipsterapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hipsterapp-postgresql:5432/hipsterapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hipsterapp-postgresql:
        extends:
            file: postgresql.yml
            service: hipsterapp-postgresql
